// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAM2s-9ydnIweezID5pook2Yk5wrpVOM',
    appId: '1:312577911178:web:800bd67c6614a5f8a78073',
    messagingSenderId: '312577911178',
    projectId: 'how-are-you-745e4',
    authDomain: 'how-are-you-745e4.firebaseapp.com',
    storageBucket: 'how-are-you-745e4.firebasestorage.app',
    measurementId: 'G-G93PFC4PVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRQpTbLqoYV4TLu1WKaCQiGpYq-c56qY',
    appId: '1:312577911178:android:210ad94bf3c9606fa78073',
    messagingSenderId: '312577911178',
    projectId: 'how-are-you-745e4',
    storageBucket: 'how-are-you-745e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVup2mBPtdkSUyQcPzSZrLl3h0Bs5oOxI',
    appId: '1:312577911178:ios:a67d393128434d8ca78073',
    messagingSenderId: '312577911178',
    projectId: 'how-are-you-745e4',
    storageBucket: 'how-are-you-745e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVup2mBPtdkSUyQcPzSZrLl3h0Bs5oOxI',
    appId: '1:312577911178:ios:a67d393128434d8ca78073',
    messagingSenderId: '312577911178',
    projectId: 'how-are-you-745e4',
    storageBucket: 'how-are-you-745e4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyAM2s-9ydnIweezID5pook2Yk5wrpVOM',
    appId: '1:312577911178:web:dd4a23e4962c0c51a78073',
    messagingSenderId: '312577911178',
    projectId: 'how-are-you-745e4',
    authDomain: 'how-are-you-745e4.firebaseapp.com',
    storageBucket: 'how-are-you-745e4.firebasestorage.app',
    measurementId: 'G-VP9ZY81FXT',
  );
}
